import Header from "@/components/Header";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-inter relative">
        <main className="relative overflow-hidden">{children}</main>
      </body>
    </html>
  );
}
